name: Telegram Auto Post

on:
  workflow_dispatch:
  schedule:
    - cron: "/5 * * * *"

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: pip install requests pikepdf

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          DEST_CHANNEL: ${{ secrets.DEST_CHANNEL }}
          FEED_URL: ${{ secrets.FEED_URL }}
          FOLLOW_LINE: "📢 Follow TELEGRAM https://t.me/RAJBSTC2026 | WHATSAPP https://whatsapp.com/channel/0029Vb6cxwVId7nVeD0xTW1n"
        run: python bot.py

      - name: Commit last.txt state
        run: |
          if [ -f last.txt ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add last.txt
            git commit -m "Update state" || echo "No changes"
            git push
          fi
